ALTER SESSION SET CONTAINER = xepdb1;
CREATE USER dersao IDENTIFIED BY 986960440
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;
GRANT CREATE SESSION TO dersao;
GRANT CREATE TABLE TO dersao;
GRANT CREATE INDEX TO dersao;
GRANT CREATE SEQUENCE TO dersao;
COMMIT;
EXIT;
